"""init

Revision ID: 5007879dc127
Revises: 
Create Date: 2026-02-13 16:25:51.084752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5007879dc127'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tick_length_seconds', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_tick_processed', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('join_code', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_join_code'), ['join_code'], unique=True)

    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_game_id'), ['game_id'], unique=False)

    op.create_table('panel_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('panel_key', sa.String(length=64), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'panel_key', name='uq_panel_state')
    )
    with op.batch_alter_table('panel_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_state_game_id'), ['game_id'], unique=False)

    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_user_id'), ['user_id'], unique=False)

    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('type_key', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('location_json', sa.JSON(), nullable=False),
    sa.Column('owner_player_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['owner_player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_game_id'))

    op.drop_table('entity')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_user_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_id'))

    op.drop_table('player')
    with op.batch_alter_table('panel_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_state_game_id'))

    op.drop_table('panel_state')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_game_id'))

    op.drop_table('event_log')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_join_code'))

    op.drop_table('game')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
